package tela;

import java.text.Normalizer;
import java.util.ArrayList;
import java.util.Random;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;



public class TelaJogo extends javax.swing.JFrame {
    /**
     * Creates new form TelaJogo
     */
    public TelaJogo() {
        initComponents();
        palavraSorteada.setVisible(false);
        jLabel6.setVisible(false);
        setLocationRelativeTo(null);
    }
    
    ArrayList<String> palavras = new ArrayList();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        palavraSecreta = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        botaoSalvar = new javax.swing.JButton();
        botaoSair = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        letraChute = new javax.swing.JTextField();
        botaoChutar = new javax.swing.JButton();
        palavraAdivinhar = new javax.swing.JLabel();
        botaoComecar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        vidas = new javax.swing.JLabel();
        palavraSorteada = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Candara Light", 3, 52)); // NOI18N
        jLabel1.setText("Jogo da Forca");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel2.setFont(new java.awt.Font("Candara Light", 0, 18)); // NOI18N
        jLabel2.setText("Informe a palavra secreta:");

        botaoSalvar.setFont(new java.awt.Font("Candara Light", 0, 14)); // NOI18N
        botaoSalvar.setText("Salvar");
        botaoSalvar.setPreferredSize(new java.awt.Dimension(308, 264));
        botaoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvarActionPerformed(evt);
            }
        });

        botaoSair.setFont(new java.awt.Font("Candara Light", 0, 14)); // NOI18N
        botaoSair.setText("Sair");
        botaoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSairActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Candara Light", 0, 24)); // NOI18N
        jLabel3.setText("Informe uma letra:");

        letraChute.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        botaoChutar.setFont(new java.awt.Font("Candara Light", 0, 18)); // NOI18N
        botaoChutar.setText("Chutar");
        botaoChutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoChutarActionPerformed(evt);
            }
        });

        palavraAdivinhar.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        palavraAdivinhar.setText("?????");

        botaoComecar.setFont(new java.awt.Font("Candara Light", 1, 24)); // NOI18N
        botaoComecar.setText("Começar");
        botaoComecar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoComecarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Candara Light", 0, 36)); // NOI18N
        jLabel4.setText("Vidas:");

        vidas.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        vidas.setText("5");

        palavraSorteada.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        palavraSorteada.setText("palavraSorteada");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/icon.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel6.setText("A palavra era:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(340, 340, 340)
                        .addComponent(palavraAdivinhar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botaoChutar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(letraChute, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(palavraSecreta, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botaoComecar, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(vidas, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(103, 103, 103)
                                .addComponent(jLabel1)
                                .addGap(203, 203, 203)
                                .addComponent(botaoSair, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(palavraSorteada)
                .addGap(171, 171, 171))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(botaoSair)
                    .addComponent(jLabel5))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(palavraAdivinhar)
                        .addGap(181, 181, 181)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(letraChute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(vidas))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoChutar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(palavraSecreta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(botaoSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoComecar))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(palavraSorteada)
                    .addComponent(jLabel6))
                .addGap(65, 65, 65))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSairActionPerformed
        int opcao = JOptionPane.showConfirmDialog(null, "Deseja sair do jogo?", "Atenção",JOptionPane.YES_NO_OPTION);
        if (opcao == JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_botaoSairActionPerformed

    //Método que irá remover acentos e caracteres especiais da palavra digitada
    public static String corrigirString(String texto){
        String nfdNormalizedString = Normalizer.normalize(texto, Normalizer.Form.NFD);
        Pattern pattern = Pattern.compile("\\p{InCombiningDiacriticalMarks}+");
        return pattern.matcher(nfdNormalizedString).replaceAll("");
    }
    
    private void botaoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarActionPerformed
        if (palavraSecreta.getText().isEmpty()){ //Ver se existe texto digitado
            JOptionPane.showMessageDialog(null, "Informe uma palavra!");
        } else {
            String texto = palavraSecreta.getText();
            palavras.add(corrigirString(texto)); //Adiciona a palabra digitada no Arraylist após utilizar o método para corrigir a palavra
            JOptionPane.showMessageDialog(null, "Palavra gravada!");
            palavraSecreta.setText("");
            palavraSecreta.requestFocus(); 
        }
    }//GEN-LAST:event_botaoSalvarActionPerformed

    private void botaoComecarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoComecarActionPerformed
        int t = palavras.size(); //pegar o tamanho do ArrayList
        Random random = new Random();
        int numeroRandom = random.nextInt(t); //gerando número random
        palavraSorteada.setText(palavras.get(numeroRandom).toUpperCase()); //usando o número random para pegar a posição (palavra) no Arraylist
        
        char[] palavraEscolhida = palavraSorteada.getText().toCharArray();
        String secreto = "";
        for(int i = 0; i < palavraEscolhida.length; i++){        
            secreto = secreto + "-";
        }
        palavraAdivinhar.setText(secreto);
        letraChute.requestFocus();    
    }//GEN-LAST:event_botaoComecarActionPerformed

    private void botaoChutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoChutarActionPerformed
        if (letraChute.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Digite uma Letra!");
            letraChute.requestFocus();
        } else {
            char[] palavraQuebrada = palavraSorteada.getText().toUpperCase().toCharArray();
            String secreto = palavraAdivinhar.getText();
            StringBuilder adivinha = new StringBuilder(secreto);
            
            char letra = letraChute.getText().toUpperCase().charAt(0);
                
            boolean encontrou = false;
            for(int i = 0; i < palavraQuebrada.length; i++){
                if (palavraQuebrada[i] == letra) {
                    adivinha.setCharAt(i, letra);
                    JOptionPane.showMessageDialog(null, "Acertou");
                    palavraAdivinhar.setText(adivinha.toString());  
                    encontrou = true;                    
                }
            }
        
            int qtdVidas = Integer.parseInt(vidas.getText());            
            if (encontrou == false) {
                qtdVidas--;
                vidas.setText(Integer.toString(qtdVidas));
                JOptionPane.showMessageDialog(null, "Errou");                
            }
            
            if (palavraSorteada.getText().equals(palavraAdivinhar.getText())) {
                JOptionPane.showMessageDialog(null, "Você acertou toda a palavra!");  
                palavraAdivinhar.setText("?????");
                vidas.setText("5");
            }
            
            if (qtdVidas == 0) {
                JOptionPane.showMessageDialog(null, "Você perdeu!");
                palavraSorteada.setVisible(true);
                jLabel6.setVisible(true);
                palavraAdivinhar.setText("Univates");                
                vidas.setText("5");
                int opcao = JOptionPane.showConfirmDialog(null, "Jogar novamente ?", "Você perdeu",JOptionPane.YES_NO_OPTION);
                if (opcao == JOptionPane.NO_OPTION){
                    System.exit(0);
                } else if (opcao == JOptionPane.YES_OPTION){
                    palavraSorteada.setVisible(false);
                    jLabel6.setVisible(false);
                }
            }       
        letraChute.setText("");
        letraChute.requestFocus();
        }
    }//GEN-LAST:event_botaoChutarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaJogo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoChutar;
    private javax.swing.JButton botaoComecar;
    private javax.swing.JButton botaoSair;
    private javax.swing.JButton botaoSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField letraChute;
    private javax.swing.JLabel palavraAdivinhar;
    private javax.swing.JTextField palavraSecreta;
    private javax.swing.JLabel palavraSorteada;
    private javax.swing.JLabel vidas;
    // End of variables declaration//GEN-END:variables
}
